name: ci

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'
        cache: 'npm'
    - run: npm ci
    - run: npx playwright install
    - run: npm test
  
    - uses: actions/upload-artifact@master
      with:
        name: allure-results
        path: allure-results
        retention-days: 20
        
    - name: Get Allure history
      uses: actions/checkout@v2
      if: always()
      continue-on-error: true
      with:
        ref: gh-pages
        path: gh-pages
    
    - name: Test marketplace action
      uses: simple-elf/allure-report-action@master
      if: always()
      id: allure-report
      with:
        allure_results: allure-results
        gh_pages: gh-pages
        allure_report: allure-report
        allure_history: allure-history
        keep_reports: 20
    - name: Generate Report
      if: always()
      run: npm run allureGenerate # Name of the allure generate script
    - name: Upload Results
      uses: actions/upload-artifact@v1
      if: always()        
      with:
          name: allure-results
          path: ./allure-results # Name of the folder with allure results 
                   
    - name: Publishing Allure artifact to Github Actions
      uses: actions/upload-artifact@v2
      if: always()
      with:
           name: allure-report
           path: allure-report       
    - name: Deploy report
      uses: JamesIves/github-pages-deploy-action@4.1.4
      if: always()
      with:
          branch: gh-pages # The branch the action should deploy to.
          folder: allure-report # The folder the action should deploy.

    
